name: 'Dependency Review'
on: [pull_request]

permissions:
 contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
        uses: test1css/app.css@main
        with:
         # ([String]). Representing a path to a configuration file local to the repository or in an external repository.
 
         # Syntax for an external file: OWNER/REPOSITORY/FILENAME@BRANCH
         config-file: '[OWNER]/[REPOSITORY]/app.css'

         # ([Token]) Use if your configuration file resides in a private external repository.
         # Possible values: Any GitHub token with read access to the private external repository.  
         external-repo-token: 'ghp_123456789abcde'
